export const AUDIT_ACTIONS = {
  // Auth
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_CREATED: 'USER_CREATED',
  USER_LOCKED: 'USER_LOCKED',
  USER_UNLOCKED: 'USER_UNLOCKED',

  // Plans
  PLAN_CREATED: 'PLAN_CREATED',
  PLAN_UPDATED: 'PLAN_UPDATED',
  PLAN_SUSPENDED: 'PLAN_SUSPENDED',
  PLAN_DELETED: 'PLAN_DELETED',
  PLAN_COMPLETED: 'PLAN_COMPLETED',

  // Messages
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGE_UPLOADED: 'MESSAGE_UPLOADED',
  MESSAGE_RELEASED: 'MESSAGE_RELEASED',
  MESSAGE_REVOKED: 'MESSAGE_REVOKED',
  MESSAGE_VIEWED: 'MESSAGE_VIEWED',

  // Verifiers
  VERIFIER_INVITED: 'VERIFIER_INVITED',
  VERIFIER_ACCEPTED: 'VERIFIER_ACCEPTED',
  VERIFIER_DECLINED: 'VERIFIER_DECLINED',
  VERIFIER_REVOKED: 'VERIFIER_REVOKED',

  // Release
  RELEASE_REQUESTED: 'RELEASE_REQUESTED',
  RELEASE_APPROVED: 'RELEASE_APPROVED',
  RELEASE_DENIED: 'RELEASE_DENIED',
  RELEASE_FINALIZED: 'RELEASE_FINALIZED',

  // Recipients
  RECIPIENT_NOTIFIED: 'RECIPIENT_NOTIFIED',
  RECIPIENT_ACCESS_GRANTED: 'RECIPIENT_ACCESS_GRANTED',
  RECIPIENT_ACCESS_REVOKED: 'RECIPIENT_ACCESS_REVOKED',
} as const;

export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_PATTERN = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]/;

export const MAX_VIDEO_SIZE_BYTES = 2 * 1024 * 1024 * 1024; // 2GB
export const ALLOWED_VIDEO_TYPES = [
  'video/mp4',
  'video/webm',
  'video/quicktime',
  'video/x-matroska',
];

export const RECIPIENT_TOKEN_EXPIRY_HOURS = 24;
export const VERIFIER_TOKEN_EXPIRY_DAYS = 7;

export const RATE_LIMITS = {
  AUTH: { max: 10, window: 60 * 1000 }, // 10 per minute
  API: { max: 100, window: 60 * 1000 }, // 100 per minute
  UPLOAD: { max: 5, window: 60 * 60 * 1000 }, // 5 per hour
  RELEASE: { max: 3, window: 60 * 60 * 1000 }, // 3 per hour
} as const;

